# Generated by Django 3.2.3 on 2021-06-06 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.IntegerField(default='', unique=True)),
                ('name', models.CharField(default=None, max_length=30)),
                ('department', models.CharField(default=None, max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('estimated_hrs', models.IntegerField(default=None, null=True)),
            ],
        ),
    ]
