# Generated by Django 3.2.3 on 2021-06-06 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='name',
            field=models.CharField(default='', max_length=30),
        ),
    ]
