# Generated by Django 3.2.3 on 2021-06-12 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_milestone_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='milestone',
            name='start_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
