# Generated by Django 3.2.3 on 2021-06-12 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_alter_task_assigned_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='assigned_by',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
