# Generated by Django 3.2.3 on 2021-07-01 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_task_assigned_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='department',
            field=models.CharField(default='', max_length=30),
        ),
    ]
