# Generated by Django 3.2.3 on 2021-07-01 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_auto_20210701_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='weightage',
            field=models.IntegerField(default=0),
        ),
    ]
