# Generated by Django 3.2.3 on 2021-07-01 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_projects_weightage'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projects',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
