# Generated by Django 3.2.3 on 2021-07-01 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_auto_20210702_0140'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='created_date',
        ),
    ]
