# Generated by Django 3.2.3 on 2022-02-14 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_remove_projects_created_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Milestone_templates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('milestone', models.CharField(default='', max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='Task_templates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(default='', max_length=1024)),
                ('mid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.milestone_templates')),
            ],
        ),
    ]
