# Generated by Django 3.2.3 on 2023-07-17 09:14

from django.db import migrations, models
import django.db.models.deletion
import file_management.storage


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_milestone_templates_task_templates'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(default='', max_length=1024)),
                ('type', models.CharField(choices=[('radio', 'Radio Button'), ('text', 'Text Field')], default='text', max_length=50)),
                ('attachment', models.FileField(blank=True, default=None, null=True, storage=file_management.storage.OverwriteStorage(), upload_to='checklist_questions/')),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.CharField(default='', max_length=1024)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('question', models.ManyToManyField(blank=True, to='projects.Question')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='options',
            field=models.ManyToManyField(blank=True, to='projects.QuestionOption'),
        ),
        migrations.CreateModel(
            name='Checklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=1024)),
                ('remarks', models.TextField(default='')),
                ('is_deleted', models.BooleanField(default=False)),
                ('section', models.ManyToManyField(blank=True, to='projects.Section')),
            ],
        ),
        migrations.AddField(
            model_name='projects',
            name='checklists',
            field=models.ManyToManyField(blank=True, default=[], to='projects.Checklist'),
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(default='', null=True)),
                ('remarks', models.TextField(blank=True, default='', null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('checklist', models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.DO_NOTHING, to='projects.checklist')),
                ('project', models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.DO_NOTHING, to='projects.projects')),
                ('question', models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.DO_NOTHING, to='projects.question')),
                ('section', models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.DO_NOTHING, to='projects.section')),
            ],
            options={
                'unique_together': {('question', 'checklist', 'section')},
            },
        ),
    ]
