# Generated by Django 3.2.3 on 2024-02-07 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0017_auto_20240207_0641'),
    ]

    operations = [
        migrations.AddField(
            model_name='milestone_templates',
            name='department',
            field=models.CharField(default='', max_length=100),
        ),
    ]
