# Generated by Django 3.2.3 on 2024-02-29 12:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0018_milestone_templates_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='uid',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='milestone_templates',
            name='department',
            field=models.CharField(default='', max_length=1024),
        ),
        migrations.AlterUniqueTogether(
            name='answer',
            unique_together={('question', 'checklist', 'section')},
        ),
    ]
