# Generated by Django 3.2.3 on 2024-03-26 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0019_auto_20240229_1234'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='estimated_hrs',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='quotted_hours',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='weightage',
        ),
        migrations.RemoveField(
            model_name='task',
            name='estimated_hrs',
        ),
    ]
