# Generated by Django 3.2.3 on 2024-03-27 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0020_auto_20240326_1331'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='p_code',
            field=models.CharField(blank=True, max_length=25),
        ),
    ]
