# Generated by Django 3.2.3 on 2024-03-27 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0021_projects_p_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='pid',
        ),
    ]
