# Generated by Django 3.2.3 on 2021-06-08 09:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='timesheet_submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=50)),
                ('eid', models.IntegerField(default=None)),
                ('project', models.CharField(default=None, max_length=50)),
                ('date', models.DateField(default=None)),
                ('task', models.CharField(default=None, max_length=50)),
                ('hours', models.IntegerField(default=None)),
                ('status', models.CharField(default=None, max_length=50)),
                ('comment', models.CharField(default=None, max_length=500)),
                ('empid', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('project_name', models.ManyToManyField(to='projects.Projects')),
            ],
        ),
    ]
