# Generated by Django 3.2.3 on 2021-07-01 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0003_remove_timesheet_submission_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timesheet_submission',
            name='task',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
    ]
