# Generated by Django 3.2.3 on 2021-07-01 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0004_alter_timesheet_submission_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timesheet_submission',
            name='comment',
            field=models.CharField(default=None, max_length=1500),
        ),
    ]
