# Generated by Django 3.2.3 on 2021-07-01 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0005_alter_timesheet_submission_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timesheet_submission',
            name='project_name',
        ),
    ]
