# Generated by Django 3.2.3 on 2021-07-01 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0006_remove_timesheet_submission_project_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timesheet_submission',
            old_name='project',
            new_name='project_name',
        ),
        migrations.AddField(
            model_name='timesheet_submission',
            name='project_id',
            field=models.IntegerField(default=None),
        ),
    ]
