# Generated by Django 3.2.3 on 2021-07-01 22:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_remove_projects_created_date'),
        ('timeline', '0007_auto_20210702_0344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timesheet_submission',
            name='project_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.projects'),
        ),
    ]
