# Generated by Django 3.2.3 on 2021-07-02 19:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0008_alter_timesheet_submission_project_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timesheet_submission',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
