# Generated by Django 3.2.3 on 2021-12-21 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0009_alter_timesheet_submission_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='timesheet_submission',
            name='location',
            field=models.CharField(default=None, max_length=25),
        ),
    ]
