# Generated by Django 3.2.3 on 2023-12-02 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0010_timesheet_submission_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timesheet_submission',
            name='project_name',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='timesheet_submission',
            name='task',
            field=models.CharField(default=None, max_length=250, null=True),
        ),
    ]
