# Generated by Django 3.2.3 on 2023-12-05 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0011_auto_20231202_0656'),
    ]

    operations = [
        migrations.AddField(
            model_name='timesheet_submission',
            name='milestone',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
