# Generated by Django 3.2.3 on 2024-02-07 05:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0016_alter_answer_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('timeline', '0012_timesheet_submission_milestone'),
    ]

    operations = [
        migrations.CreateModel(
            name='submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=None)),
                ('hours', models.IntegerField(default=None)),
                ('comment', models.CharField(default=None, max_length=1500)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('submission_date', models.DateTimeField(auto_now_add=True)),
                ('submission_status', models.CharField(default=None, max_length=50, null=True)),
                ('pid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.projects')),
                ('tid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.task')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
