# Generated by Django 3.2.3 on 2024-02-07 12:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0017_auto_20240207_0641'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('timeline', '0013_submission'),
    ]

    operations = [
        migrations.AddField(
            model_name='timesheet_submission',
            name='submission_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='timesheet_submission',
            name='submission_status',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='timesheet_submission',
            name='task_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='projects.task'),
        ),
        migrations.AddField(
            model_name='timesheet_submission',
            name='uid',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
