# Generated by Django 3.2.3 on 2024-02-07 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0014_auto_20240207_1235'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timesheet_submission',
            name='eid',
        ),
        migrations.RemoveField(
            model_name='timesheet_submission',
            name='location',
        ),
        migrations.RemoveField(
            model_name='timesheet_submission',
            name='milestone',
        ),
        migrations.RemoveField(
            model_name='timesheet_submission',
            name='name',
        ),
        migrations.RemoveField(
            model_name='timesheet_submission',
            name='project_id',
        ),
        migrations.RemoveField(
            model_name='timesheet_submission',
            name='project_name',
        ),
        migrations.RemoveField(
            model_name='timesheet_submission',
            name='task',
        ),
    ]
