# Generated by Django 3.2.3 on 2021-05-24 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customemployeedetails',
            name='eid',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
