# Generated by Django 3.2.3 on 2021-05-28 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0002_alter_customemployeedetails_eid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customemployeedetails',
            name='phone',
            field=models.CharField(default='None', max_length=10, unique=True),
        ),
    ]
