# Generated by Django 3.2.3 on 2021-07-01 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0003_alter_customemployeedetails_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customemployeedetails',
            name='department',
            field=models.CharField(default='', max_length=30),
        ),
    ]
