# Generated by Django 3.2.3 on 2021-07-01 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0004_alter_customemployeedetails_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customemployeedetails',
            name='phone',
            field=models.CharField(default='None', max_length=10, null=True),
        ),
    ]
