# Generated by Django 3.2.3 on 2024-02-07 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0005_alter_customemployeedetails_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customemployeedetails',
            old_name='group',
            new_name='role',
        ),
    ]
