# Generated by Django 3.2.3 on 2024-02-07 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0007_customemployeedetails_reporting_to'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customemployeedetails',
            name='name',
        ),
    ]
