# Generated by Django 3.2.3 on 2024-02-10 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0008_remove_customemployeedetails_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customemployeedetails',
            name='department',
        ),
    ]
