# Generated by Django 3.2.3 on 2024-02-29 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0010_remove_customemployeedetails_eid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customemployeedetails',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
    ]
