# Generated by Django 3.2.3 on 2021-08-10 10:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='document_manage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_name', models.CharField(default='', max_length=100)),
                ('file_name', models.CharField(default='', max_length=100)),
                ('updated_date', models.DateField(default=django.utils.timezone.now)),
                ('version', models.CharField(default='', max_length=10)),
                ('file', models.FileField(upload_to='document/')),
            ],
        ),
    ]
