# Generated by Django 3.2.3 on 2021-08-12 06:48

from django.db import migrations, models
import file_management.storage


class Migration(migrations.Migration):

    dependencies = [
        ('file_management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document_manage',
            name='file_name',
        ),
        migrations.AlterField(
            model_name='document_manage',
            name='file',
            field=models.FileField(storage=file_management.storage.OverwriteStorage(), upload_to='document/'),
        ),
    ]
