# Generated by Django 3.2.3 on 2022-02-20 06:30

from django.db import migrations, models
import django.utils.timezone
import file_management.storage


class Migration(migrations.Migration):

    dependencies = [
        ('file_management', '0002_auto_20210812_1218'),
    ]

    operations = [
        migrations.CreateModel(
            name='feeds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('title', models.CharField(default='Title', max_length=100)),
                ('Description', models.CharField(default='', max_length=500)),
                ('file', models.FileField(storage=file_management.storage.OverwriteStorage(), upload_to='images/')),
            ],
        ),
    ]
