# Generated by Django 3.2.3 on 2022-07-17 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_management', '0003_feeds'),
    ]

    operations = [
        migrations.CreateModel(
            name='category_project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='lessonlearnt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Project', models.CharField(max_length=50)),
                ('Category', models.CharField(max_length=50)),
                ('Owner', models.CharField(max_length=50)),
                ('Event', models.CharField(max_length=50)),
                ('Limitations', models.CharField(max_length=50)),
                ('Actions', models.CharField(max_length=50)),
                ('Status', models.CharField(max_length=50)),
                ('Remark', models.CharField(max_length=50)),
            ],
        ),
    ]
