# Generated by Django 3.2.3 on 2022-07-24 06:30

from django.db import migrations, models
import file_management.storage


class Migration(migrations.Migration):

    dependencies = [
        ('file_management', '0004_category_project_lessonlearnt'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonlearnt',
            name='file_lesson',
            field=models.FileField(blank=True, default=None, null=True, storage=file_management.storage.OverwriteStorage(), upload_to='lessonlearnt/'),
        ),
    ]
