# Generated by Django 3.2.3 on 2022-08-17 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_management', '0005_lessonlearnt_file_lesson'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonlearnt',
            name='Actions',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='lessonlearnt',
            name='Event',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='lessonlearnt',
            name='Limitations',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='lessonlearnt',
            name='Owner',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='lessonlearnt',
            name='Remark',
            field=models.CharField(max_length=500),
        ),
    ]
